x <- read.csv("household_power_consumption.txt", header = T, sep = ';', na.strings = "?", nrows = 2075259, check.names = F, stringsAsFactors = F, comment.char = "", quote = '\"')
View(x)
y <- subset(x, Date %in% c("1/2/2007", "2/2/2007"))
y$Date <- as.Date(y$Date, format = "%d/%m/%y")
ydate <- paste(as.Date(y$Date), y$Time)
y$ydate <- as.POSIXct(ydate)
with(y, plot(Global_active_power ~ ydate, type = "l", xlab = "", ylab = "Global Active Power (kilowatts)"))
dev.copy(png,file="plot2.png", width=480, height=480)
dev.off()