x <- read.csv("household_power_consumption.txt", header = T, sep = ';', na.strings = "?", nrows = 2075259, check.names = F, stringsAsFactors = F, comment.char = "", quote = '\"')
View(x)
y <- subset(x, Date %in% c("1/2/2007", "2/2/2007"))
y$Date <- as.Date(y$Date, format = "%d/%m/%y")
ydate <- paste(as.Date(y$Date), y$Time)
y$ydate <- as.POSIXct(ydate)
with(y,(plot(Sub_metering_1~ydate, type = "l", col = "black", xlab = "", ylab = "Energy sub metering")))
with(y,(lines(Sub_metering_2~ydate, col="red")))
with(y,(lines(Sub_metering_3~ydate, col="blue")))
legend("topright", lty = 1, lwd = 2, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file="plot3.png",width=480,height=480)
dev.off()
